/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedRbacRouteImport } from './routes/_authenticated/rbac'
import { Route as AuthenticatedMyRequestsRouteImport } from './routes/_authenticated/my-requests'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as PublicLocationIdRouteImport } from './routes/public.location.$id'
import { Route as AuthenticatedStockCreateRouteImport } from './routes/_authenticated/stock_.create'
import { Route as AuthenticatedRequestsCreateRouteImport } from './routes/_authenticated/requests_.create'
import { Route as AuthenticatedStockEditIdRouteImport } from './routes/_authenticated/stock_.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRbacRoute = AuthenticatedRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyRequestsRoute = AuthenticatedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicLocationIdRoute = PublicLocationIdRouteImport.update({
  id: '/public/location/$id',
  path: '/public/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStockCreateRoute =
  AuthenticatedStockCreateRouteImport.update({
    id: '/stock_/create',
    path: '/stock/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsCreateRoute =
  AuthenticatedRequestsCreateRouteImport.update({
    id: '/requests_/create',
    path: '/requests/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockEditIdRoute =
  AuthenticatedStockEditIdRouteImport.update({
    id: '/stock_/edit/$id',
    path: '/stock/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock': typeof AuthenticatedStockRoute
  '/requests/create': typeof AuthenticatedRequestsCreateRoute
  '/stock/create': typeof AuthenticatedStockCreateRoute
  '/public/location/$id': typeof PublicLocationIdRoute
  '/stock/edit/$id': typeof AuthenticatedStockEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/rbac': typeof AuthenticatedRbacRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stock': typeof AuthenticatedStockRoute
  '/requests/create': typeof AuthenticatedRequestsCreateRoute
  '/stock/create': typeof AuthenticatedStockCreateRoute
  '/public/location/$id': typeof PublicLocationIdRoute
  '/stock/edit/$id': typeof AuthenticatedStockEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/my-requests': typeof AuthenticatedMyRequestsRoute
  '/_authenticated/rbac': typeof AuthenticatedRbacRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/requests_/create': typeof AuthenticatedRequestsCreateRoute
  '/_authenticated/stock_/create': typeof AuthenticatedStockCreateRoute
  '/public/location/$id': typeof PublicLocationIdRoute
  '/_authenticated/stock_/edit/$id': typeof AuthenticatedStockEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/forbidden'
    | '/locations'
    | '/logs'
    | '/my-requests'
    | '/rbac'
    | '/requests'
    | '/staff'
    | '/stock'
    | '/requests/create'
    | '/stock/create'
    | '/public/location/$id'
    | '/stock/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/forbidden'
    | '/locations'
    | '/logs'
    | '/my-requests'
    | '/rbac'
    | '/requests'
    | '/staff'
    | '/stock'
    | '/requests/create'
    | '/stock/create'
    | '/public/location/$id'
    | '/stock/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/forbidden'
    | '/_authenticated/locations'
    | '/_authenticated/logs'
    | '/_authenticated/my-requests'
    | '/_authenticated/rbac'
    | '/_authenticated/requests'
    | '/_authenticated/staff'
    | '/_authenticated/stock'
    | '/_authenticated/requests_/create'
    | '/_authenticated/stock_/create'
    | '/public/location/$id'
    | '/_authenticated/stock_/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicLocationIdRoute: typeof PublicLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rbac': {
      id: '/_authenticated/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof AuthenticatedRbacRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-requests': {
      id: '/_authenticated/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthenticatedMyRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public/location/$id': {
      id: '/public/location/$id'
      path: '/public/location/$id'
      fullPath: '/public/location/$id'
      preLoaderRoute: typeof PublicLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stock_/create': {
      id: '/_authenticated/stock_/create'
      path: '/stock/create'
      fullPath: '/stock/create'
      preLoaderRoute: typeof AuthenticatedStockCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests_/create': {
      id: '/_authenticated/requests_/create'
      path: '/requests/create'
      fullPath: '/requests/create'
      preLoaderRoute: typeof AuthenticatedRequestsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock_/edit/$id': {
      id: '/_authenticated/stock_/edit/$id'
      path: '/stock/edit/$id'
      fullPath: '/stock/edit/$id'
      preLoaderRoute: typeof AuthenticatedStockEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMyRequestsRoute: typeof AuthenticatedMyRequestsRoute
  AuthenticatedRbacRoute: typeof AuthenticatedRbacRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedRequestsCreateRoute: typeof AuthenticatedRequestsCreateRoute
  AuthenticatedStockCreateRoute: typeof AuthenticatedStockCreateRoute
  AuthenticatedStockEditIdRoute: typeof AuthenticatedStockEditIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMyRequestsRoute: AuthenticatedMyRequestsRoute,
  AuthenticatedRbacRoute: AuthenticatedRbacRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedRequestsCreateRoute: AuthenticatedRequestsCreateRoute,
  AuthenticatedStockCreateRoute: AuthenticatedStockCreateRoute,
  AuthenticatedStockEditIdRoute: AuthenticatedStockEditIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicLocationIdRoute: PublicLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
